### ISSUE TITLE
simple question for future xls-support plan! [:

### ISSUE THREAD

**Issue by exitist** [justkawal/excel#97]
Hello sir! i'm flutter newbie using your plug-in so lovely! First of all, thank you so much for sharing awesome library with light license!! Now in my code, this library is being used to deal with excel files from my main corporate bank account.

Then I faced a classic issue for this library with reading(importing/decoding) xls format into flutter engine. I understand that there are bunch of closed issues with the format, replied: `I'll update the ReadMe with a note that Only XLSX files are supported.`; This is fully enough to see how things are going on, but is is true that huge old-aged institutions, especially banks still use old xls format, and it really seems like they won't change the format to xlsx with my little tiny requests. Since the situations, i'm currently manually converting xls to xlsx all the time.

So, even though the format is not supported in the time of writing, i think it would be awesome if you can make it clear whether there is any plan to add xls support or not, and if not, it would be really thankful if you can simply share the reason why it is tough to support xls, so that other developers might start their own work to deal with the deprecated extension and might merge their cool future codes into this plug-in, which is why this plug-in is Open Source! Thank you for reading [:

**Comment by justkawal** [comment]
**I would love to see into the xls thing**, but for the time being I don't have any plans,

I barely get any time as I've to work 18 hours a day in different private company projects, so as to improve and sharpen my skills in order to move overseas.

I'm maintaining **excel** and all other plugins on my free time or weekends.

I'm truly sorry for delays in resolving the issues, I would try to do the best I can to implement this feature in the near future. 🚀

**Comment by exitist** [comment]
Cool. Just wanna say that your current jobs on the package are already amazing enough! Thank u for the answer [:
